[package]
name = "fast-matrix-vector-multiplication"
version = "0.1.0"
authors = ["Andy Oertel <aoer@hrz.tu-chemnitz.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "*"
petgraph = "*"
graph6 = "*"
rayon = "*"