[package]
name = "fast-matrix-vector-multiplication"
version = "0.1.0"
authors = ["Andy Oertel <andy.oertel@informatik.tu-chemnitz.de>"]
edition = "2018"

[lib]
name = "ultrametric_multiplication"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
nalgebra = "*"
ptree = "*"
numpy = "*"
ndarray = "*"
pyo3 = "*"

[dev-dependencies]
rand = "*"
criterion = "*"
csv = "*"

[[bench]]
name = "single_multiplication"
harness = false

[[bench]]
name = "multiple_multiplication"
harness = false

[[bench]]
name = "jacobi_method"
harness = false