[package]
name = "fast-matrix-vector-multiplication"
version = "0.1.0"
authors = ["Andy Oertel <andy.oertel@informatik.tu-chemnitz.de>"]
edition = "2018"

[lib]
name = "ultrametric_multiplication"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
nalgebra = "*"
ptree = "*"
numpy = "*"
ndarray = "*"
pyo3 = "*"
rand = "*"
petgraph = "*"
rayon = "*"

[dev-dependencies]
graph6 = "*"
criterion = "*"
csv = "*"

[[bench]]
name = "multiplication_test"
harness = false

[[bench]]
name = "property_check_test"
harness = false

[[bench]]
name = "performance"
harness = false

[[bench]]
name = "performance_multiple"
harness = false

[[bench]]
name = "jacobi_test"
harness = false