[package]
name = "fast-matrix-vector-multiplication"
version = "0.1.0"
authors = ["Andy Oertel <andy.oertel@informatik.tu-chemnitz.de>"]
edition = "2018"

[lib]
name = "ultrametric_multiplication"
path = "src/lib.rs"

[dependencies]
nalgebra = "*"
ptree = "*"

[dev-dependencies]
petgraph = "*"
graph6 = "*"
rayon = "*"
rand = "*"
criterion = "*"

[[bench]]
name = "multiplication_test"
harness = false